"use strict";

const fs = require("fs");
const path = require("path");

const root = __dirname;
const sourceHtml = fs.readFileSync(path.join(root, "index.html"), "utf8");
const sourceCss = fs.readFileSync(path.join(root, "styles.css"), "utf8");
const sourceJs = fs.readFileSync(path.join(root, "app.js"), "utf8");

const styleTag = `<style>\n${sourceCss}\n</style>`;
const safeJs = sourceJs.replace(/<\/script/gi, "<\\/script");
const scriptTag = `<script>\n${safeJs}\n</script>`;

let bundled = sourceHtml
  .replace('<link rel="stylesheet" href="styles.css">', styleTag)
  .replace('<script src="app.js"></script>', scriptTag)
  .replace(
    "<!doctype html>",
    "<!doctype html>\n<!-- Generated by build_single_html.js. Edit index.html, styles.css, or app.js, then rebuild. -->",
  );

if (bundled.includes('href="styles.css"') || bundled.includes('src="app.js"')) {
  throw new Error("Bundling failed: external source references remain.");
}

const outputPath = path.join(root, "SpellBack.html");
fs.writeFileSync(outputPath, bundled, "utf8");
console.log(`Built ${path.basename(outputPath)} (${Buffer.byteLength(bundled)} bytes)`);
